/// Flutter icons BankbooLightIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BankbooLightIcon
///      fonts:
///       - asset: fonts/BankbooLightIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BankbooLightIcon {
  BankbooLightIcon._();

  static const _kFontFam = 'BankbooLightIcon';
  static const _kFontPkg = null;

  static const IconData wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_up = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alpha_up = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alpha_down = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_v = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out_alt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in_alt = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sack = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check_alt = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave_alt = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_alt = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_smile = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_alt = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marked_alt = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marked = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_square = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_text = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_dollar = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_front = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list_check = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_scan = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_read = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballot_check = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballot = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_dollar = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_check = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vote_yea = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
